apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base


helmCharts:
  - name: admin-portal-app
    repo: ""
    releaseName: admin-portal-app
    version: 0.1.0
    valuesFile: ./../../../../external-charts/admin-portal-app/values-staging.yaml
    includeCRDs: false
    namespace: admin-portal-app

images:
- name: pocprodacr1.azurecr.io/app
  newTag: v0.0.1 # Initial version, will be updated by image updater